export const STORAGE_KEYS = {
  THEME: "sonic-flow-theme",
  FONT_SIZE: "sonic-flow-font-size",
  RIGHT_SIDEBAR_WIDTH: "sonic-flow-subsidebar-width",
  NOTIFICATIONS_ENABLED: "sonic-flow-notifications-enabled",
  LEFT_SIDEBAR_OPEN: "sonic-flow-left-sidebar-open",
  RIGHT_SIDEBAR_OPEN: "sonic-flow-right-sidebar-open",
  LEFT_SIDEBAR_WIDTH: "sonic-flow-left-sidebar-width",
  LANGUAGE: "sonic-flow-language",
  MEMO_TAB: "sonic-flow-memo-tab",
  EFFECT_VOLUME: "sonic-flow-effect-volume",
  ACTIVE_CALENDAR_ID: "sonic-flow-active-calendar-id",
  TASK_TREE_FOLDER_FILTER: "sonic-flow-task-tree-folder-filter",
  TASK_TREE_SORT_MODE: "sonic-flow-task-tree-sort-mode",
  CALENDAR_MODE: "sonic-flow-calendar-mode",
  AUDIO_MODE: "sonic-flow-audio-mode",
  ACTIVE_PLAYLIST_ID: "sonic-flow-active-playlist-id",
} as const;
