export const STORAGE_KEYS = {
  TASK_TREE: 'sonic-flow-task-tree',
  SOUND_MIXER: 'sonic-flow-sound-mixer',
  WORK_DURATION: 'sonic-flow-work-duration',
  THEME: 'sonic-flow-theme',
  FONT_SIZE: 'sonic-flow-font-size',
  RIGHT_SIDEBAR_WIDTH: 'sonic-flow-subsidebar-width',
  NOTIFICATIONS_ENABLED: 'sonic-flow-notifications-enabled',
  LEFT_SIDEBAR_OPEN: 'sonic-flow-left-sidebar-open',
  RIGHT_SIDEBAR_OPEN: 'sonic-flow-right-sidebar-open',
  BREAK_DURATION: 'sonic-flow-break-duration',
  LONG_BREAK_DURATION: 'sonic-flow-long-break-duration',
  SESSIONS_BEFORE_LONG_BREAK: 'sonic-flow-sessions-before-long-break',
  MIGRATION_DONE: 'sonic-flow-migration-done',
  MEMOS: 'sonic-flow-memos',
  CUSTOM_SOUNDS: 'sonic-flow-custom-sounds',
} as const;
